  name: Build, Push Docker image and Deploy to Cloud Run

  on:
    push:
      branches:
        - main

  jobs:
    build-and-deploy:
      runs-on: ubuntu-latest

      steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          . venv/bin/activate
          pytest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        if: success()
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        if: success()
        run: |
          docker build -t gonzagomezp1/backend:latest .
          docker push gonzagomezp1/backend:latest

      - name: Get Docker image digest
        if: success()
        id: get_digest
        run: echo "DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' gonzagomezp1/backend:latest)" >> $GITHUB_ENV

      - name: Logout from Docker Hub
        if: success()
        run: docker logout

      - name: Authenticate to Google Cloud
        if: success()
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        if: success()
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ingenieriadesoftware3

      - name: Deploy to Cloud Run
        if: success()
        run: |
          gcloud config set run/region us-central1
          gcloud run deploy backend \
            --image ${{ env.DIGEST }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --cpu 0.5 \
            --memory 128Mi \
            --min-instances 0 \
            --max-instances 5 \
            --timeout 900
